export const FETCH_FACILITIES_START = "FETCH_FACILITIES_START";
export const FETCH_FACILITIES_SUCCESS = "FETCH_FACILITIES_SUCCESS";
export const FETCH_FACILITIES_FAIL = "FETCH_FACILITIES_FAIL";

export const FETCH_ADMIN_HIERARCHIES_START = "FETCH_ADMIN_HIERARCHIES_START";
export const FETCH_ADMIN_HIERARCHIES_SUCCESS =
  "FETCH_ADMIN_HIERARCHIES_SUCCESS";

export const FETCH_ALL_FACILITY_COUNT_SUCCESS =
  "FETCH_ALL_FACILITY_COUNT_SUCCESS";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";

export const BUILD_NODE_INDEX_SUCCESS = "BUILD_NODE_INDEX_SUCCESS";

export const TRANSFORM_HIERARCHIES_FOR_TREE_VIEW =
  "TRANSFORM_HIERARCHIES_FOR_TREE_VIEW";

export const FILTER_QUERY_ADDED = "FILTER_QUERY_ADDED";

export const FILTER_QUERY_RESET = "FILTER_QUERY_RESET";
export const FILTER_FIELD_VALUE_RESET = "FILTER_FIELD_VALUE_RESET";

export const DIGEST_BY_FACILITY_TYPE_LOADED = "DIGEST_BY_FACILITY_TYPE_LOADED";

export const DIGEST_BY_OPERATIONAL_STATUS_LOADED =
  "DIGEST_BY_OPERATIONAL_STATUS_LOADED";

export const DIGEST_BY_OWNERSHIP_STATUS_LOADED =
  "DIGEST_BY_OWNERSHIP_STATUS_LOADED";

export const FETCH_FILTER_FIELDS = "FETCH_FILTER_FIELDS";
export const UPDATE_FILTER_FIELDS_VALUE = "UPDATE_FILTER_FIELDS_VALUE";
export const REMOVE_FILTER = "REMOVE_FILTER";
